import type { Metadata } from "next";
import "./globals.css";

import { Poppins } from "next/font/google";
import SocialSidebar from "./components/socialSidebar/social-sidebar";
import { NavigationMenuDemo } from "./components/navbar/navbar";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={poppins.className} lang="en">
      <body>
        <NavigationMenuDemo></NavigationMenuDemo>
        <SocialSidebar></SocialSidebar>
        {children}
      </body>
    </html>
  );
}
